version: "3.8"

services:
  pgsql:
    image: postgres:15.3-alpine
    container_name: '${POSTGRES_CONTAINER_NAME:-pgsql-tech-school}'
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB:-POSTGRES_DB}'
      TZ: '${APP_TIMEZONE:-Asia/Taipei}'
    networks:
      - tech-school
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      retries: 3
      timeout: 5s

networks:
  tech-school:
    driver: bridge